### ISSUE TITLE
encoding parameter for utf-8

### ISSUE THREAD

**Issue by Uchastnick** [yannikkellerde/config_to_object#1]
Hi!
Would you like to add to the code the ability to open a configuration file in utf-8 encoding?

For example:
use "encoding" parameter in the "load_config (..., encoding)" procedure.

1. and then use like this
>>>
config_obj.read(filename, encoding=encoding)

2. or as the second way:
>>>
import codecs
...
config_obj.readfp(codecs.open(filename, "r", encoding))

**Comment by Uchastnick** [comment]
Danke!

Perhaps, if you have free time, you can add a couple more things:

1. Specify the default value of the "encoding" parameter explicitly 'utf-8'
instead of None
2. Add one more optional parameter that allows interpolation inside the
ini-file:

```
from configparser import ExtendedInterpolation

config = ConfigParser(interpolation=ExtendedInterpolation())
```

Have a good day!


пт, 29 июл. 2022 г. в 22:05, yannikkellerde ***@***.***>:

**Comment by yannikkellerde** [comment]
Hey Uchastnick,
Happy to see that my library is usefull to someone besides myself :). However, I don't plan to actively maintain this repo anymore. If you need these changes implemented, feel free to fork and make a pull request (Or just monkeypatch them in your local installation).

**Comment by Uchastnick** [comment]
Yes, you're right. Thanks!


ср, 3 авг. 2022 г. в 08:54, yannikkellerde ***@***.***>:
